project:
  type: website
  output-dir: docs
website:
  page-footer:
    left: |
      &copy; Renee Nicholson, 2025<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

  title: "Renee Nicholson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - posts.qmd
    background: "#0e5e28"
    search: true
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
editor: visual





